### PR TITLE
My first open source contribution.

### PR DESCRIPTION
**Pull request by Prithvi2310**

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts [**here**](https://github.com/Design-and-Code/Opensource-practice/pull/59/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](https://dsc.gg/designandcode). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

**Comment by Prithvi2310** [comment]
Hey there, I have updated the README.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🎉

**Comment by Prithvi2310** [comment]
Hello
When will this PR be merged?

**Pull request merged**
